# Managed by repository-settings/app
# https://github.com/repository-settings/app

repository:
  description: "Local search/fetch/extract plumbing, exposed as an MCP stdio server"
  homepage: "https://github.com/arclabs561/webpipe"
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

  topics:
    - cli
    - mcp
    - rust
    - search
    - tooling
    - web-scraping
